name = "Quantity Based Discounts"
client_id = "078005936813f139cea0d930d5d6122f"
application_url = "https://shopify-discount-app.webvijayi.com"
embedded = true

[access_scopes]
# Combined scopes in one string, comma-separated
scopes = "write_products,read_products,read_price_rules,write_price_rules,read_discounts,write_discounts,read_themes,write_themes,read_script_tags,write_script_tags"

[auth]
redirect_urls = [
    "https://shopify-discount-app.webvijayi.com/auth/callback",
    "https://shopify-discount-app.webvijayi.com/auth/tokens"
]

[webhooks]
api_version = "2024-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/webhooks"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[pos]
embedded = false
