name = "Quantity Based Discounts"
client_id = "078005936813f139cea0d930d5d6122f"
application_url = "https://shopify-discount-app.webvijayi.com"
embedded = true

[access_scopes]
# Read and modify products and their variants
scopes = "write_products,read_products,write_discounts,read_discounts"

[auth]
redirect_urls = [
    "https://shopify-discount-app.webvijayi.com/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
