# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Quantity based discounts"
client_id = "078005936813f139cea0d930d5d6122f"
application_url = "https://harbour-linking-www-howto.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_price_rules,write_price_rules,read_discounts,write_discounts,read_themes,write_themes,read_script_tags,write_script_tags"

[auth]
redirect_urls = [
  "https://harbour-linking-www-howto.trycloudflare.com/auth/callback",
  "https://harbour-linking-www-howto.trycloudflare.com/auth/shopify/callback",
  "https://harbour-linking-www-howto.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "webvijayi.myshopify.com"
