name = "Quantity Based Discounts"
client_id = "078005936813f139cea0d930d5d6122f"
application_url = "https://shopify-discount-app.webvijayi.com"
embedded = true

[access_scopes]
# Product access for applying discounts
scopes = "write_products,read_products"

# Price rules and discounts
scopes = "read_price_rules,write_price_rules"
scopes = "read_discounts,write_discounts"

# Theme and script access for widget injection
scopes = "read_themes,write_themes"
scopes = "read_script_tags,write_script_tags"

[auth]
redirect_urls = [
    "https://shopify-discount-app.webvijayi.com/auth/callback",
    "https://shopify-discount-app.webvijayi.com/auth/tokens"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
